apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mtcnnfd.fullname" . }}
  labels:
    app: "{{ template "mtcnnfd.fullname" . }}"
    chart: "{{ template "mtcnnfd.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: "{{ template "mtcnnfd.fullname" . }}"
      release: {{ .Release.Name | quote }}
  {{- if .Values.updateStrategy }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "mtcnnfd.fullname" . }}"
        chart: "{{ template "mtcnnfd.chart" . }}"
        release: {{ .Release.Name | quote }}
{{- if or .Values.podAnnotations .Values.metrics.enabled }}
      annotations:
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.metrics.podAnnotations }}
{{ toYaml .Values.metrics.podAnnotations | indent 8 }}
{{- end }}
{{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
{{- include "mtcnnfd.imagePullSecrets" . | indent 6 }}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "status.localhost"
      containers:
      - name: mtcnnfd
        image: {{ template "mtcnnfd.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        # env:
        ports:
        - name: http
          containerPort: 8080
        # need implement this probe for HA deployment
#         livenessProbe:
#           httpGet:
#             path: /health
#             port: "http"
#             {{- if .Values.livenessProbeHeaders }}
#             httpHeaders:
# {{ toYaml .Values.livenessProbeHeaders | indent 14 }}
#             {{- end }}
# {{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
          exec:
            command:
              - curl
              - -X POST
              - "http://localhost:8080/init"
{{ toYaml .Values.readinessProbe | indent 10 }}
        # volumeMounts:
        resources:
{{ toYaml .Values.resources | indent 10 }}

{{- if .Values.sidecars }}
{{ toYaml .Values.sidecars | indent 6 }}
{{- end }}

      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end -}}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
